services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: friesland
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.simple
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=friesland
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres_data: