version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: friesland_postgres
    environment:
      POSTGRES_DB: friesland_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - friesland_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Dashboard Laravel (API Backend)
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: friesland_dashboard
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY_HERE
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=friesland_dashboard
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1,flutter_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dashboard:/var/www/html
      - dashboard_storage:/var/www/html/storage
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - friesland_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application Flutter (optionnel pour tests)
  flutter_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: friesland_flutter
    environment:
      - API_BASE_URL=http://dashboard:80/api/v1
    ports:
      - "8080:8080"
    depends_on:
      - dashboard
    networks:
      - friesland_network
    volumes:
      - ./lib:/app/lib
      - ./assets:/app/assets
      - ./pubspec.yaml:/app/pubspec.yaml

  # Redis pour le cache (optionnel)
  redis:
    image: redis:7-alpine
    container_name: friesland_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - friesland_network
    command: redis-server --appendonly yes

  # Nginx pour proxy reverse (optionnel)
  nginx:
    image: nginx:alpine
    container_name: friesland_nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dashboard/public:/var/www/html/public
    depends_on:
      - dashboard
    networks:
      - friesland_network

  # Monitoring avec Adminer pour la BDD
  adminer:
    image: adminer:latest
    container_name: friesland_adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - friesland_network

volumes:
  postgres_data:
    driver: local
  dashboard_storage:
    driver: local
  redis_data:
    driver: local

networks:
  friesland_network:
    driver: bridge