services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: friesland_postgres
    environment:
      POSTGRES_DB: friesland_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Dashboard Laravel avec API et Filament
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: friesland_dashboard
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:base64:abcdefghijklmnopqrstuvwxyz1234567890
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=friesland_dashboard
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    ports:
      - "80:80"
    volumes:
      - ./dashboard:/var/www/html
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local