name: friesland_dashboard
description: Application Flutter pour la gestion des visites commerciales Friesland Bonnet Rouge
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # API et réseau principal remplace Firebase
  # Les fonctionnalités Firebase sont maintenant gérées par l'API REST

  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Géolocalisation et Géofencing
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.1.0
  geodesy: ^0.4.0
  location: ^5.0.3

  # Cartes et Navigation
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.2.2

  # Stockage local
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0

  # Capture d'images
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  image: ^4.1.3

  # Interface utilisateur
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_svg: ^2.0.9

  # Graphiques et Analytics
  fl_chart: ^0.65.0

  # Export et Rapports
  pdf: ^3.10.6
  excel: ^4.0.1
  csv: ^5.0.2
  printing: ^5.11.1

  # Réseau et Connectivité
  http: ^1.1.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

  # Utilitaires
  intl: ^0.19.0
  uuid: ^4.2.1
  crypto: ^3.0.3
  convert: ^3.1.1
  collection: ^1.18.0

  # Date et Temps
  table_calendar: ^3.0.9

  # Formulaires et Validation
  reactive_forms: ^16.1.1
  form_validator: ^2.1.1

  # Animations
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0

  # JSON et Sérialisation
  json_annotation: ^4.8.1
  
  # Architecture
  get_it: ^7.6.4
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true